#!/bin/bash
#
# Bash script for check_mk using hyg-usb v0.1 from Macareux Labs.
# https://github.com/macareux-labs/hyg-usb_linux
#
# The data is returned to the script, and 2 threshold are setup : WARNING and ALARM.
#
# 0 is OK
# 1 is WARNING
# 2 is critical
#
#
# HOWTO :
# ((Data is printed as <<local>> if your run check_mk -d in console))
#
# 1) Place this script into your check_mk plugin, on the hosts where the hyg-usb is pluged
#   => Example: /usr/lib/check_mk_agent/local
#
# 2) Check eXecutable : chmod +x hyg_hygro
#
# 3) Setup the service in check_mk
#
#
# LICENCE
# This project is placed under the MIT License. See LICENSE file for details
#
#


####################################
# SETUP HERE
#
#
# Hygro for the WARNING
WARNING=50
# Hygro for the ALARM
CRITICAL=95
# Path for the binary
HYG_USB_PATH="/opt/hyg-usb"
#
#
# End of SETUP
####################################

HYGRO_LONG=`${HYG_USB_PATH}/hyg-usb -H | awk '{print $4}' |  cut -c1-5`
HYGRO_SHORT=${HYGRO_LONG%.*}

if [ $HYGRO_SHORT -lt 50 ]; then
        status=0
        statustxt=OK
elif [ $HYGRO_SHORT -lt 95 ]; then
        status=1
        statustxt=WARNING
        else
        status=2
        statustxt=CRITICAL
fi

echo "$status Hygrometrie hygro=$HYGRO_LONG $statusok- $HYGRO_LONG catched and $HYGRO_SHORT returned."
